site_name: Lectron Documentation
theme:
  name: material #readthedocs
  language: tr                     
  features:
    - navigation.tabs
    - navigation.expand       
    - navigation.instant
    - navigation.sections     
    - toc.integrate
    - content.tabs.linked     
    - header.autohide         
    - announce.dismiss   
  font:
    text: Roboto
    code: Fira Code   
  icon:
    repo: fontawesome/brands/github
    logo: material/robot-industrial
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Light Mode

nav:
  - Jetson Custom Board: md/Jetson.md
  - Raspberry Pi Custom Board: md/Raspberry.md
  - Lectron Ari: md/LectronAri.md
  - Lectron Ebabil: md/LectronEbabil.md

markdown_extensions:
  - admonition                 # !!! info, warning vs
  - pymdownx.details           # ??? collapsible bloklar
  - pymdownx.superfences       # iç içe kod blokları
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true           # kod bloklarında satır numarası
  - pymdownx.inlinehilite      # satır içi kod vurgusu
  - pymdownx.tabbed:
      alternate_style: true    # tab’li içerik
  - pymdownx.tasklist:
      custom_checkbox: true    # [ ] / [x] checklist
  - toc:
      permalink: true          # başlıklarda # linki